import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import Header from '../components/header/header';
import imageLoader from '../imageLoader'
import styles from '../styles/Home.module.css'
import { Character, GetCharacterResults } from '../types'

const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.characters}>
        {characters.map((character) => {
          return (
            <div
              className={styles.character}
              key={character.id}>
              <Link
                href={`/characters/${character.id}`}>
                <a>
                  <h3 className={styles.text}>{character.name}</h3>
                </a>
              </Link>
              <div className={styles.image}>
                <Image
                  loader={imageLoader}
                  unoptimized
                  src={character.image}
                  alt={character.name}
                  width='200%'
                  height='200%'
                />
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}
// this runs when you are initially loading page
export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character")
  const { results }: GetCharacterResults = await res.json();

  return {
    props: {
      characters: results
    }
  }
}

// getServerSideProps runs for a dynamic webpage

export default Home